
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WpfApp1
{

using System;
    using System.Collections.Generic;
    
public partial class Baskets
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Baskets()
    {

        this.ProductList = new HashSet<ProductList>();

    }


    public int Id { get; set; }

    public Nullable<int> IdUser { get; set; }

    public Nullable<System.DateTime> OrderDate { get; set; }

    public Nullable<int> Price { get; set; }

    public string Address { get; set; }

    public string Desc { get; set; }

    public Nullable<bool> Confirm { get; set; }

    public string Payment { get; set; }



    public virtual Users Users { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ProductList> ProductList { get; set; }

}

}
