//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductList
    {
        public int Id { get; set; }
        public Nullable<int> IdBasket { get; set; }
        public Nullable<int> IdProduct { get; set; }
        public Nullable<int> Amount { get; set; }
    
        public virtual Baskets Baskets { get; set; }
        public virtual Products Products { get; set; }

        public override string ToString()
        {
            return $"{Products.Name} X {Amount} шт. Цена={Products.Price}";
        }

        
        
    }
}
